version: '3.8'

networks:
  main:

services:
  metabase:
    image: metabase/metabase:v0.44.5
    container_name: mb-metabase
    networks:
      - main
    ports:
      - '3000:3000'
    environment:
      MB_DISABLE_SESSION_THROTTLE: 'true'
      MB_PASSWORD_COMPLEXITY: weak
      MB_SEND_EMAIL_ON_FIRST_LOGIN_FROM_NEW_DEVICE: 'false'
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:3000/api/health | grep -q ok"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  postgres:
    image: postgres:14
    container_name: mb-postgres
    networks:
      - main
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
